### ISSUE TITLE
Primary Introductory Example wouldn't compile or run 

### ISSUE THREAD

**Issue by cefn** [regadas/trino-js-client#559]
In the introductory documentation the following snippet is offered...

https://github.com/regadas/trino-js-client/blob/97e599adb0ebd0d424efcb365d8c95337acaca3a/README.md?plain=1#L42-L44

A followup snippet explains how you consume the result...

https://github.com/regadas/trino-js-client/blob/97e599adb0ebd0d424efcb365d8c95337acaca3a/README.md?plain=1#L50-L52

I don't know how the example offered would ever compile and run, since the `for await...of` signature requires an AsyncIterator. See the following typescript playground.

<img width="1076" alt="image" src="https://github.com/regadas/trino-js-client/assets/159819/27a136a0-f7a7-48a3-aadf-ce37c71e68a9">

**Comment by regadas** [comment]
Hello 👋 

Not really sure how you are testing things, but at first glance you might be using the wrong Iterator in your tests; 

Have a look @ https://github.com/regadas/trino-js-client/blob/97e599adb0ebd0d424efcb365d8c95337acaca3a/src/index.ts#L299; this is the right one.

Thanks for reaching out.

**Comment by cefn** [comment]
Thanks, Filipe. 

Yes, it hadn't occurred to me that the Typescript core synchronous [Iterator](https://github.com/microsoft/TypeScript/blob/b9c71c3fc39f7cbafa82f8aa6f1d3b8a86e27ede/src/lib/es2015.iterable.d.ts#L23) name had been overloaded in the trino-js-client module, with an implementation which subclasses from `AsyncIterator`. The example doesn't indicate the import path of `Iterator`.

I suppose if people want to use typescript in their code then they could import your `Iterator` aliased as `TrinoIterator`. Makes sense now.
